version: '2'
services:
  web:
    image: nginx:alpine
    # ports:
    #   - 80:80
    depends_on: 
      - php
      - mysql
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/html:/var/www/html
    restart: always

  php:
    image: php:7.2-fpm-alpine
    volumes:
      - ./src/html:/var/www/html
    restart: always

  mysql:
    image: mariadb
    volumes:
      - ./src/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=TRUE
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    restart: always
